### ISSUE TITLE
GLTF Textures not binding

### ISSUE THREAD

**Issue by Protoxy22** [TimLee9024/MCglTF#1]
Hello, I really like your work it's amazing !
I tested yesterday and had missing textures on my model, the console has no errors and I correctly added "extras" with "resourceLocation" in each "images"/"buffer".

Another question, how can I use an embedded .glb without setting this extras parameters and having the textures binded in game ?

Thank you

![image](https://user-images.githubusercontent.com/30320751/157019290-09afbe07-a897-4ec3-a44a-d9bf6a546140.png)

**Comment by TimLee9024** [comment]
Did you have properly setup "extras" properties like "baseColorTexture", "normalTexture"... in the materials?
https://github.com/TimLee9024/MCglTF-Example/blob/308ea752a5d74f826da20adcf2c42fbeb43c0f29/src/main/resources/assets/mcgltf/models/item/water_bottle.gltf#L158

It will not use default material properties provided by glTF spec, because of the shader pack's special texture packing.
For example BSL's SEUS: "baseColorTexture" as albedo map, "normalTexture" as DirectX normal map, "specularTexture" as (R)glossiness/(G)metallic/(B)emissive stregth map
https://github.com/TheDuckCow/MCprep/issues/78
BTW: You will need to fix materialGbuffers.glsl in BSL ShaderPack. Detailed tutorial will be avalible in the Wiki page later.

As for .glb, you won't need to setup those extras properties. The embedded resources like images and buffers will be load from uri as usual.

But anyway, I am still dealing with some compatibilty issues with ShaderMod by Optifine. I really should finish documentation before I publish source code and release on curseforge. I am sorry about that...

**Comment by Protoxy22** [comment]
Ok thank you very much for your answer.

I think I will use your library to make a new version of my gun mod if I am allowed to.

Actually I have two problems and a suggestion:

- There is bug with two of models I tested, there is a sort of desync (I just replaced the model name of `TileEntityItemStackRendererItemExample` everything is by default.
Video (in-game): https://streamable.com/fg3a4b
Video (blender): https://streamable.com/lj3dkd

- I have a console error when using using .glb files (which are more easy to use)
My Blender parameters export:
![image](https://user-images.githubusercontent.com/30320751/157130018-33d16e12-8766-44bc-b2b0-e2603baa7798.png)
Console error: https://pastebin.com/zuYms5UN


- And lastly, only thing I will need, If I may give a suggestion is a possibility to have transitions betweens animations with a sort of an interpolation between the last keyframe of an anim and the first keyframe of a new one.
So in general, have a better accessibility of the AnimatedModel object


I am sorry for If I wrote too many, I am really enthusiast of your work since I'm searching for a library like this for years !

Greets
Protoxy

**Comment by Protoxy22** [comment]
And I have this error when using a .glb

Export parameters:
![image](https://user-images.githubusercontent.com/30320751/157130018-33d16e12-8766-44bc-b2b0-e2603baa7798.png)


Error:
`[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: java.lang.IllegalArgumentException: ByteBuffer is not direct
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at org.lwjgl.BufferChecks.checkDirect(BufferChecks.java:115)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at org.lwjgl.opengl.GL15.glBufferData(GL15.java:141)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.timlee9024.mcgltf.RenderedGltfModel.bindArrayBufferViewModel(RenderedGltfModel.java:1726)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.timlee9024.mcgltf.RenderedGltfModel.processMeshPrimitiveModel(RenderedGltfModel.java:559)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.timlee9024.mcgltf.RenderedGltfModel.processNodeModel(RenderedGltfModel.java:194)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.timlee9024.mcgltf.RenderedGltfModel.lambda$new$5(RenderedGltfModel.java:110)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at java.util.ArrayList.forEach(ArrayList.java:1257)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.timlee9024.mcgltf.RenderedGltfModel.<init>(RenderedGltfModel.java:101)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.timlee9024.mcgltf.MCglTF$1.lambda$onResourceManagerReload$1(MCglTF.java:126)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at java.util.ArrayList.forEach(ArrayList.java:1257)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.timlee9024.mcgltf.MCglTF$1.onResourceManagerReload(MCglTF.java:121)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at net.minecraftforge.client.resource.ISelectiveResourceReloadListener.onResourceManagerReload(ISelectiveResourceReloadListener.java:33)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:121)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.timlee9024.mcgltf.MCglTF.onEvent(MCglTF.java:114)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:639)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:757)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at net.minecraft.client.Minecraft.init(Minecraft.java:535)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at net.minecraft.client.Minecraft.run(Minecraft.java:378)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at net.minecraft.client.main.Main.main(Main.java:118)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at net.minecraftforge.legacydev.Main.start(Main.java:86)
[23:37:18] [Client thread/INFO] [STDERR]: [com.timlee9024.mcgltf.MCglTF$1:lambda$onResourceManagerReload$1:132]: 	at net.minecraftforge.legacydev.MainClient.main(MainClient.java:29)
`

**Comment by TimLee9024** [comment]
Hope these answer your questions :)

1. Did you have mutiple animations in glTF? The example code provided is to [play every animation in "animations" simultaneously](https://github.com/TimLee9024/MCglTF-Example/blob/f37b161d5242d060df78899f6cbfe714205eeb34/src/main/java/com/timlee9024/mcgltf/example/TileEntityItemStackRendererItemExample.java#L51), you can change to what you want.
If this is not the issue, maybe try out the [FBX2glTF](https://github.com/facebookincubator/FBX2glTF) and convert the .gltf into .glb by [VSCode's glTF tools extension](https://marketplace.visualstudio.com/items?itemName=cesium.gltf-vscode).
This is the workflow I use, because some exporter seem to have werid problems on exported model. (Previously I use babylon.js glTF exporter for 3ds Max, but it cause game BSOD for unknown reason during early development)

2. It seem like jglTF allocate indirect ByteBuffer for binary chunk in RawBinaryGltfDataReaderV1 and RawBinaryGltfDataReaderV2 which cause the errors.
I forget to testing .glb after recent change made by jglTF few month ago...

3. It sound like you want a procedural generated animation "C" which is created from last frame of "A" and first frame "B".
In theory you can done this in your Renderer class which have implements IGltfModelReceiver like pseudo code below:
``` java
protected List<Runnable> commands;

protected List<Animation> animations;

protected List<NodeModel[]> nodeThatNeedToApplyTransform;

protected List<float[]> transformLastFrameA;

protected List<float[]> transformFirstFrameB;

protected float transitionTime; //This field can be desrialize from "extras" inside everywhere of glTF

@Override
public void onModelLoaded(RenderedGltfModel renderedModel) {
	GltfModel gltfModel = renderedModel.gltfModel;
	animations = GltfAnimations.createModelAnimations(gltfModel.getAnimationModels());
	
	// Your Code Here: Find the required NodeModel for transformation from gltfModel.getSceneModels()
	
	Animation animA = animations.get(0); //Get Animation A
	animA.update(animA.getEndTimeS()); //Set gltfModel's current transformations from Animation A
	
	// Your Code Here: Find every current transform values needed from nodeThatNeedToApplyTransform and "copy" those float array into transformLastFrameA
	
	Animation animB = animations.get(1); //Get Animation B
	animB.update(0.0F); //Set gltfModel's current transformations from Animation B
	
	// Your Code Here: Find every current transform values needed from nodeThatNeedToApplyTransform and "copy" those float array into transformFirstFrameB
}

@Override
public void render() {
	// Your Code Here: Based on current time from tick and partial tick or some conditions,
	// set every NodeModel's transform in nodeThatNeedToApplyTransform with interpolated values from transformLastFrameA, transformFirstFrameB, and transitionTime.
	
	commands.forEach((command) -> command.run()); //Run render command
}
```

**Comment by Protoxy22** [comment]
Thank you very much, I keep you tuned :)

**Comment by Protoxy22** [comment]
Hello, I have difficulties registering the shader and the model bakes at the init of mcgltf in 1.18.2
It seems the OpenGL contexts are not accessible at the mod init thread

**Comment by TimLee9024** [comment]
This is most likely the answer:
https://gist.github.com/50ap5ud5/beebcf056cbdd3c922cc8993689428f4#shader-based-rendering
> Minecraft has moved to OpenGL 3.2 Core, which brings with it shader-based rendering.

https://www.khronos.org/opengl/wiki/OpenGL_Context#Context_types

> OpenGL version 3.0 introduced the idea of deprecating functionality. Many OpenGL functions were declared deprecated, which means that users should avoid using them because they may be removed from later API versions. OpenGL 3.1 removed almost all of the functionality deprecated in OpenGL 3.0. This includes the Fixed Function Pipeline.

For example, things like GL11.glPushAttrib, GL11.glPopAttrib, GL11.glVertexPointer, glClientActiveTexture from early OpenGL version are no longer available. There will have a lots of internal change made to MCglTF, in order to adapt into new rendering system of Minecraft since 1.17.

Currently, I have no schedule about to porting MCglTF into 1.18.2. (Maybe finish documentations in MCglTF wiki first? Or just waiting Forge and Optifine become more stable as they claim)

BTW: MCglTF is now available on curseforge https://www.curseforge.com/minecraft/mc-mods/mcgltf

**Comment by Protoxy22** [comment]
Thank you very much for your detailed answers

**Comment by Protoxy22** [comment]
The GLB files loads fine, but the textures (colorMap) still doesn't work (tested in 1.12.2)
.glb file (exported from Blender): [akm.zip](https://github.com/TimLee9024/MCglTF/files/8238771/akm.zip)

Preview: https://streamable.com/yml9hd

**Comment by TimLee9024** [comment]
Seem like you forgot to add "[extras](https://github.com/TimLee9024/MCglTF-Example/blob/308ea752a5d74f826da20adcf2c42fbeb43c0f29/src/main/resources/assets/mcgltf/models/item/water_bottle.gltf#L157)" properties in materials again.

[akm_fix.zip](https://github.com/TimLee9024/MCglTF/files/8239075/akm_fix.zip)
![Fix](https://user-images.githubusercontent.com/39574697/158048134-d5549afb-7139-4c07-a354-b65ffd2fc54a.png)

**Comment by Protoxy22** [comment]
Ok, I thought it was not necessary, because you said:
> As for .glb, you won't need to setup those extras properties. The embedded resources like images and buffers will be load from uri as usual.

Now I understand, materials index (colorMap, normalMap, specularMap) need to be defined manually.

It would be good to find a way to import .glb without this extra parameters, because it's a bit of pain to manually add those.

Suggestion: for example the colorMap index will be automatically took from the default `pbrMetallicRoughness` if there is no extras parameter set :)
```
      "pbrMetallicRoughness": {
        "baseColorTexture": {
          "index": 0
        }
      }
```

Another suggestion is to be able to apply opengl matrix transformation (translation, rotation, scale) for specific NodeModel on the scene when the Runnable of the rendering is triggered, it would help me a lot.

I am sorry if I suggest too much things, I'll try to continue on a fork repo and make pull requests if you want

**Comment by TimLee9024** [comment]
>Suggestion: for example the colorMap index will be automatically took from if there is no extras parameter set :)

Unfortunately not. There are two reasons:
1. [glTF V1](https://github.com/KhronosGroup/glTF/tree/main/specification/1.0#materials-and-shading) and glTF V2 have a lot's of different in "materials". You can't not dircetly define those V2 properties into V1 material, it won't pass glTF V1 validator and will not be deserialized by jglTF.
2. "Normal Map" and "Specular Map" from Optifine/Shader Pack should not directly map to any of glTF V2 PBR texture properties like "normalTexture" and "metallicRoughnessTexture". They have [different diffinition](https://github.com/TimLee9024/MCglTF-Example#model-source) in each RGBA channels.

Lastly, glTF seems to encoruge people to put those application-specific properites inside "extras".
> Another suggestion is to be able to apply opengl matrix transformation (translation, rotation, scale) for specific NodeModel on the scene when the Runnable of the rendering is triggered, it would help me a lot.

Can you provide me more detailed reason for not using things like NodeModel#setTranslation, NodeModel#setMatrix?

**Comment by Protoxy22** [comment]
Because moving the matrix of a node is permanent.
With GL calls, it is only moved during the render frame and goes back to the original transform.

Well, I can save the initial transform of each nodes and apply it before the rendering ..


Do you accept donation ? I want to donate you for your amazing work
If you want my discord (if you have access): Protoxy#9631

**Comment by TimLee9024** [comment]
> Because moving the matrix of a node is permanent.
With GL calls, it is only moved during the render frame and goes back to the original transform.

But when you want to control a bone(NodeModel) for a skinned mesh, this will not work.

> Well, I can save the initial transform of each nodes and apply it before the rendering ..

AFAIK, this is much efficiant than have a OpenGL call. There are a lots of topics on internet talking about reuducing draw calls, that is why Vanilla using MatrixStack instead of glPushMatrix in 1.16.5. Beside, I have done this before in another Unity project when using with GLTFUtility.

> Do you accept donation ? I want to donate you for your amazing work

Thank you for your kindness, but I cannot take your money.
